package com.AI.enums;


public enum ConfigPropertiesEnum{

	URL, OVERRIDEREPORTS, PASSEDSTEPSSCREENSHOTS, FAILEDSTEPSSCREENSHOTS,


	RETRYFAILEDTESTS, RUNMODE, SENDRESULTTOELK,



	SELENIUMGRIDURL, ELASTICURL, BROWSER,  DOCKERURL, VERSION


}
